spring:
  application:
    name: politech-backend

  profiles:
    active: dev

  datasource:
    url:
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
  main:
    allow-circular-references: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,logfile
  endpoint:
    health:
      show-details: when-authorized

logging:
  file:
    name: logs/backend.log
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

server:
  port: 6969
  servlet:
    context-path: /api/v1
  error:
    include-message: always
    include-binding-errors: always
